config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'

  resources :contests, only: [:show, :new] do
    post "new", to: "contests#create", as: "", on: :collection
    resources :entries, only: [:new] do
      post "select_participant", to: "entries#select_participant", on: :collection
      post "new", to: "entries#create", as: "", on: :collection
    end
    resources :votes, only: [:new] do
      post "select_participant", to: "votes#select_participant", on: :collection
      post "new", to: "votes#create", as: "", on: :collection
    end
  end
  
  resources :users, only: [:show, :update] do
    resources :participants, shallow: true, only: [:create]
  end
  
  resources :votes, only: [:create]

  root to: "home#index"
end

app/models/contest.rb
class Contest < ApplicationRecord
  has_many :entries
  has_one :winning_entry, :class_name => "Entry"
  has_many :votes, through: :entries

  before_validation :set_year
  
  validates :vote_start_date, presence: true
  validates :vote_end_date, presence: true
  validates :year, presence: true
  validates :name, presence: true

  def set_year
    return if self.persisted?
    self.year = Date.today.year
  end

  def get_winners
    if votes.any?
      entries.map { |e| [e, e.votes.sum(&:rank)] }.group_by(&:last).sort_by {|k,v| k}.first.last.map(&:first)
    end
  end

  def has_entry_from(participant)
    entries.where(participant_id: participant.id).any?
  end

  def has_vote_from(participant)
    votes.where(participant_id: participant.id).any?
  end

  def accepting_entries?
    Time.zone.now < vote_start_date
  end

  def voting_active?
    Time.zone.now > vote_start_date && Time.zone.now < vote_end_date
  end

  def voting_ended?
    Time.zone.now > vote_end_date
  end

  def rank_entries
    return [[]] if entries.blank?

    tallies = {}
    entries.each do |entry|
      tallies[entry.id] = 0
    end

    votes.each do |vote|
      tallies[vote.entry_id] += vote.rank
    end

    sorted_tally = tallies.sort_by { |_, v| v }

    ranks = []
    lowest_score = sorted_tally.first[1]
    rank = 0

    sorted_tally.each do |tally|
      entry = Entry.find(tally[0])
      if tally[1] != lowest_score
        lowest_score = tally[1]
        rank += 1
      end
      ranks[rank] ||= []
      ranks[rank] << entry
    end
    ranks
  end

  def age_range
    range = "All ages"
    if min_age_limit.present?
      range = "#{min_age_limit}"
      if age_limit.present?
        range += " - #{age_limit}"
      else
        range += " and up"
      end
    elsif age_limit.present?
      range = "up to #{age_limit - 1}"
    end
    range
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def show
    @contest = Contest.find(params[:id])
    @entries =  if @contest.voting_ended?
                  @contest.rank_entries
                elsif @contest.voting_active?
                  @contest.entries
                elsif logged_in?
                  @contest.entries.where(participant: current_user.participants)
                else
                  []
                end
  end

  def new
    @contest ||= Contest.new
  end

  def create
    @contest = Contest.new(create_params)
    if @contest.save
      @entries =  if @contest.voting_ended?
        @contest.rank_entries
      else
        @contest.entries
      end
      redirect_to(@contest)
    else
      render :new, status: 422
    end
  end

private

  def create_params
    params.require(:contest).permit(:name, :age_limit, :min_age_limit, :vote_start_date, :vote_end_date)
  end
end

app/views/contests/_contest.erb
<article class="text-content">
  <h2><%= link_to "#{ contest.year } | #{ contest.name }", contest_path(contest), data: { turbo: false } %> </h2>
  <p>Age Limit: <%= contest.age_range %></p>
  <p>Voting Begins: <%= datetime_string(contest.vote_start_date) %></p>
  <p>Voting Ends: <%= datetime_string(contest.vote_end_date) %></p>
  <% if contest.voting_ended? %>
    <h3>Winners</h3>
    <p>
      First Place: <%= contest.rank_entries.first&.map { |entry| entry.participant.name }&.join(", ") %>
    </p>
    <p>
      Second Place: <%= contest.rank_entries.second&.map { |entry| entry.participant.name }&.join(", ") %>
    </p>
    <p>
      Third Place: <%= contest.rank_entries.third&.map { |entry| entry.participant.name }&.join(", ") %>
    </p>
  <% end %>
  <p>
    <%= link_to "View Entries", contest_path(contest), data: { turbo: false } %>
    <%= if !logged_in? then "| Please log in to submit an entry or vote." end %>
    <% if logged_in? && (contest.accepting_entries? || contest.voting_active?) %>
     | 
    <% end %>
    <%= if logged_in? && contest.accepting_entries? then link_to("Submit new entry", [:new, contest, :entry], data: { turbo: false }) end %>
    <%= if logged_in? && contest.voting_active? then link_to("Submit vote", [:new, contest, :vote], data: { turbo: false }) end %>
  </p>
</article>

app/views/contests/_form.erb
<div class="form-div">
  <%= form_with(model: [@contest], data: { turbo: false }) do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, required: true %>
    </div>

    <div class="field">
      <%= form.label :age_limit %>
      <%= form.number_field :age_limit %>
    </div>

    <div class="field">
      <%= form.label :min_age_limit %>
      <%= form.number_field :min_age_limit %>
    </div>

    <div class="field">
      <%= form.label :vote_start_date %>
      <%= Time.use_zone("Mountain Time (US & Canada)") { form.datetime_field(:vote_start_date, required: true) } %>
    </div>

    <div class="field">
      <%= form.label :vote_end_date %>
      <%= Time.use_zone("Mountain Time (US & Canada)") { form.datetime_field(:vote_end_date, required: true) } %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/contests/new.erb
<main class="outer-text-content">
  <article class="text-content">
    <h1>New Contest</h1>
    <%= render "form" %>
  </article>
</main>

app/views/contests/show.erb
<main class="contest-content outer-text-content">
  <article class="text-content">
    <header>
      <h1><%= @contest.name %> | <%= @contest.year %></h1>
      <p>Age Limit: <%= @contest.age_range %></p>
      <p>Voting Begins: <%= datetime_string(@contest.vote_start_date) %></p>
      <p>Voting Ends: <%= datetime_string(@contest.vote_end_date) %></p>

      <% if !logged_in? %>
        <p>Please log in to submit an entry or vote.</p>
      <% end %>

      <% if logged_in? && @contest.accepting_entries? %>
        <p><%= link_to "Submit new entry", [:new, @contest, :entry], data: { turbo: false } %></P>
      <% end %>

      <% if @contest.accepting_entries? %>
        <p>You can only see other families' entries after voting begins (no stealing ideas!). Until then, only your family's entries will appear below.</p>
      <% end %>
      
      <% if logged_in? && @contest.voting_active? %>
        <p><%= link_to "Submit vote", [:new, @contest, :vote], data: { turbo: false } %></p>
      <% end %>
    </header>
    <% if @contest.voting_ended? %>
      <% @entries.each_with_index do |entries, rank| %>
        <h2><%= (rank + 1).ordinalize %> Place</h2>
        <% entries.each do |entry| %>
          <%= render "entries/entry", entry: entry, contest: @contest %>
        <% end %>
      <% end %>
    <% else %>
      <% @entries.each do |entry| %>
        <%= render "entries/entry", entry: entry, contest: @contest %>
      <% end %>
    <% end %>
  </article>
</main>