config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'

  resources :contests, only: [:show, :new] do
    post "new", to: "contests#create", as: "", on: :collection
    resources :entries, only: [:new] do
      post "select_participant", to: "entries#select_participant", on: :collection
      post "new", to: "entries#create", as: "", on: :collection
    end
    resources :votes, only: [:new] do
      post "select_participant", to: "votes#select_participant", on: :collection
      post "new", to: "votes#create", as: "", on: :collection
    end
  end
  
  resources :users, only: [:show, :update] do
    resources :participants, shallow: true, only: [:create]
  end
  
  resources :votes, only: [:create]

  root to: "home#index"
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :participant
  belongs_to :entry

  validates :participant, presence: true
  validates :entry, presence: true
  validates :rank, presence: true
end

app/controllers/concerns/votes_controller.rb
class VotesController < ApplicationController
  def create
    
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :ensure_contest
  before_action :ensure_participant, only: [:select_participant, :create]

  def new
    unless @contest.voting_active? && logged_in?
      flash[:error] = "Voting is closed for #{@contest.name} or you are not logged in."
      redirect_to contest_path(@contest)
      return
    end
    @participants = current_user.participants.select { |p| !@contest.has_vote_from(p) }.map { |p| [p.name, p.id] }
    unless @participants.any?
      flash.now[:error] = "You don't have any participants that haven't already voted in this contest."
    end
    render :select_participant
  end

  def select_participant
    unless @contest.voting_active? && logged_in?
      flash[:error] = "Voting is closed for #{@contest.name} or you are not logged in."
      redirect_to contest_path(@contest)
      return
    end
    @entries = @contest.entries.where.not(participant: @participant)
    @ranks = 1..@entries.count
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace(:vote_form, partial: "votes/form") }
    end
  end

  def create
    unless @contest.voting_active? && logged_in?
      flash[:error] = "Voting is closed for #{@contest.name} or you are not logged in."
      redirect_to contest_path(@contest)
      return
    end

    if @contest.votes.where(participant: @participant).any?
      flash[:error] = "That participant has already voted in #{@contest.name}."
      redirect_to contest_path(@contest)
      return
    end

    @entries = @contest.entries.where.not(participant: @participant)
    @entries.each do |entry|
      rank = params["entry_#{entry.id}_rank".to_sym].to_i
      entry.rank(@participant,rank)
    end

    own_entry = @contest.entries.where(participant: @participant).first

    if own_entry.present?
      own_entry.rank(@participant, @entries.count + 1)
    end
    flash[:notice] = "Your vote was submitted successfully."
    redirect_to contest_path(@contest)
  end

  def ensure_contest
    @contest = Contest.find(params[:contest_id])
  end

  def ensure_participant
    @participant = Participant.find(params[:participant_id])
  end
end

app/views/votes/_form.erb
<%= turbo_frame_tag(:vote_form) do %>
  <h1>Voting For <%= @participant.name %></h1>
  <div class="form-div">
    <%= form_tag(contest_votes_path, data: { controller: "vote-form", turbo: false}) do %>
      <input type="hidden" name="participant_id" value="<%= @participant.id %>">
      <input type="hidden" name="vote_start_time" value="<%= Time.zone.now %>">
      <% @entries.each do |entry| %>
        <%= render "entries/entry", entry: entry, contest: @contest %>
        <div>
            <div class="field">
                <%= label_tag "Rank #{entry.title}" %><br>
                <select name="entry_<%=entry.id%>_rank" data-action="vote-form#change focus->vote-form#focus" data-vote-form-target="select" required="required">
                  <option value="0">Rank this entry...</option>
                  <%= @ranks.each do |rank| %>
                    <option value="<%= rank %>" data-vote-form-target="option"><%= rank %></option>
                  <% end %>
                </select>
            </div>
        </div>
        <hr>
        <br>
      <% end %>
      <div class="actions">
        <%= button_tag "Submit My Vote", type: 'button', data: { action: "vote-form#submit" } %>
        <span data-vote-form-target="notice"></span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/votes/select_participant.erb
<main class="outer-text-content">
  <article class="text-content">
    <%= turbo_frame_tag(:vote_form) do %>
      <h1>Voting For:</h1>
      <p>Please select a participant. Only participants that haven't yet voted can be selected.</P>
      <div class="form-div">
        <%= form_tag("select_participant", data: { controller: "form-submitter" }) do %>
          <%= select_tag :participant_id,
            options_for_select(@participants),
            prompt: "Select participant", 
            data: {
              action: "change->form-submitter#submit"
            } %>
        <% end %>
      </div>
    <% end %>
  </article>
</main>