config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'

  resources :contests, only: [:show, :new] do
    post "new", to: "contests#create", as: "", on: :collection
    resources :entries, only: [:new] do
      post "select_participant", to: "entries#select_participant", on: :collection
      post "new", to: "entries#create", as: "", on: :collection
    end
    resources :votes, only: [:new] do
      post "select_participant", to: "votes#select_participant", on: :collection
      post "new", to: "votes#create", as: "", on: :collection
    end
  end
  
  resources :users, only: [:show, :update] do
    resources :participants, shallow: true, only: [:create]
  end
  
  resources :votes, only: [:create]

  root to: "home#index"
end

app/views/layouts/_top_nav.erb
<nav class="nav-toggle pointer"
      data-action="click->toggle#toggle"
      data-toggle-target-schemes="nav-menu">
  <span class="nav-toggle-icon" 
        data-toggle-target="toggle"
        data-toggle-schemes="nav-menu|hidden-on-mobile">
    <%= icon "fas", "chevron-circle-up" %>
  </span>
  <span class="nav-toggle-icon hidden-on-mobile" 
        data-toggle-target="toggle"
        data-toggle-schemes="nav-menu|hidden-on-mobile">
    <%= icon "fas", "chevron-circle-down" %>
  </span>
</nav>
<nav class="top-nav-content hidden-on-mobile"
        data-toggle-target="toggle"
        data-toggle-schemes="nav-menu|hidden-on-mobile">
  <div class="nav-menu">
    <div class="top-nav-item">
      <%= link_to "Home", root_path, data: { turbo: "false" } %>
    </div>
    <div class="top-nav-item hidden">
      <%= link_to "New Contest", new_contest_path, data: { turbo: "false" } %>
    </div>
  </div>
  <div class="login-menu">
    <% if logged_in? %>
      <div class="top-nav-item">
        <%= link_to( "Account", "/users/account", data: { turbo: false }) %>
      </div>
      <div class="top-nav-item">
        <%= button_to 'Logout', '/auth/logout', method: :get, data: { turbo: false }, class: "login-logout-button" %>
      </div>
    <% else %>
      <div class="top-nav-item">
        <%= button_to 'Login', '/auth/auth0', method: :post, data: {turbo: false}, class: "login-logout-button" %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GingerBreadContest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="background">
    <div class="main-grid-container" data-controller="toggle">
      <%= turbo_frame_tag("nav", class: "top-nav") do %>
        <%= render "layouts/top_nav" unless @hide_navigation %>
      <% end %>
      <%= turbo_frame_tag("title", class: "main-title") do %>
        <%= image_tag("GingerbreadHouse.png")%>
        <h1 class="hidden-on-mobile">
          Ginger Bread House Contest
        </h1>
      <% end %>
      <%= turbo_frame_tag("content", class: "content") do %>
        <% if flash[:error].present? %>
          <div class="outer-text-content">
            <div class="error-text-content">
              <span>
                <%= flash[:error] %>
              </span>
            </div>
          </div>
        <% end %>
        <% if flash[:notice].present? %>
          <div class="outer-text-content">
            <div class="notice-text-content ">
              <span>
                <%= flash[:notice] %>
              </span>
            </div>
          </div>
        <% end %>
        <%= yield %>
      <% end %>
    </div>
    <div>
      <div class="snowflakes" aria-hidden="true">
        <div class="snowflake">
        ❅
        </div>
        <div class="snowflake">
        ❅
        </div>
        <div class="snowflake">
        ❆
        </div>
        <div class="snowflake">
        ❄
        </div>
        <div class="snowflake">
        ❅
        </div>
        <div class="snowflake">
        ❆
        </div>
        <div class="snowflake">
        ❄
        </div>
        <div class="snowflake">
        ❅
        </div>
        <div class="snowflake">
        ❆
        </div>
        <div class="snowflake">
        ❄
        </div>
      </div>
    </div>
    <footer>
      <a href="https://www.freepik.com/vectors/background">Background vector created by kjpargeter - www.freepik.com</a>
    </footer>
  </body>
</html>